// AUTO-GENERATED — do not edit by hand.
// Regenerate with: pnpm --filter @routeshift/shared refresh-catalog
// Source: https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json

import type { ModelPricing } from './cost-tables';

export const LITELLM_GENERATED_PRICING: ModelPricing[] = [
  { provider: "anthropic", model: "claude-3-7-sonnet-20250219", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "anthropic", model: "claude-3-haiku-20240307", input_per_million: 0.25, output_per_million: 1.25, cache_read_per_million: 0.03, cache_write_per_million: 0.3 },
  { provider: "anthropic", model: "claude-3-opus-20240229", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "anthropic", model: "claude-4-opus-20250514", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "anthropic", model: "claude-4-sonnet-20250514", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "anthropic", model: "claude-fable-5", input_per_million: 10, output_per_million: 50, cache_read_per_million: 1, cache_write_per_million: 12.5 },
  { provider: "anthropic", model: "claude-haiku-4-5", input_per_million: 1, output_per_million: 5, cache_read_per_million: 0.1, cache_write_per_million: 1.25 },
  { provider: "anthropic", model: "claude-haiku-4-5-20251001", input_per_million: 1, output_per_million: 5, cache_read_per_million: 0.1, cache_write_per_million: 1.25 },
  { provider: "anthropic", model: "claude-mythos-5", input_per_million: 10, output_per_million: 50, cache_read_per_million: 1, cache_write_per_million: 12.5 },
  { provider: "anthropic", model: "claude-mythos-preview", input_per_million: 10, output_per_million: 50, cache_read_per_million: 1, cache_write_per_million: 12.5 },
  { provider: "anthropic", model: "claude-opus-4-1", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "anthropic", model: "claude-opus-4-1-20250805", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "anthropic", model: "claude-opus-4-20250514", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "anthropic", model: "claude-opus-4-5", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "anthropic", model: "claude-opus-4-5-20251101", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "anthropic", model: "claude-opus-4-6", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "anthropic", model: "claude-opus-4-6-20260205", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "anthropic", model: "claude-opus-4-7", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "anthropic", model: "claude-opus-4-7-20260416", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "anthropic", model: "claude-opus-4-8", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "anthropic", model: "claude-opus-5", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "anthropic", model: "claude-sonnet-4-20250514", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "anthropic", model: "claude-sonnet-4-5", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "anthropic", model: "claude-sonnet-4-5-20250929", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "anthropic", model: "claude-sonnet-4-6", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "anthropic", model: "claude-sonnet-5", input_per_million: 2, output_per_million: 10, cache_read_per_million: 0.2, cache_write_per_million: 2.5 },
  { provider: "azure", model: "command-r-plus", input_per_million: 3, output_per_million: 15, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-3.5-turbo", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-3.5-turbo-0125", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-35-turbo", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-35-turbo-0125", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-35-turbo-1106", input_per_million: 1, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-35-turbo-16k", input_per_million: 3, output_per_million: 4, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-35-turbo-16k-0613", input_per_million: 3, output_per_million: 4, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4", input_per_million: 30, output_per_million: 60, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4-0125-preview", input_per_million: 10, output_per_million: 30, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4-0613", input_per_million: 30, output_per_million: 60, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4-1106-preview", input_per_million: 10, output_per_million: 30, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4-32k", input_per_million: 60, output_per_million: 120, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4-32k-0613", input_per_million: 60, output_per_million: 120, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4-turbo", input_per_million: 10, output_per_million: 30, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4-turbo-2024-04-09", input_per_million: 10, output_per_million: 30, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4-turbo-vision-preview", input_per_million: 10, output_per_million: 30, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4.1", input_per_million: 2, output_per_million: 8, cache_read_per_million: 0.5, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4.1-2025-04-14", input_per_million: 2, output_per_million: 8, cache_read_per_million: 0.5, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4.1-mini", input_per_million: 0.4, output_per_million: 1.6, cache_read_per_million: 0.1, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4.1-mini-2025-04-14", input_per_million: 0.4, output_per_million: 1.6, cache_read_per_million: 0.1, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4.1-nano", input_per_million: 0.1, output_per_million: 0.4, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4.1-nano-2025-04-14", input_per_million: 0.1, output_per_million: 0.4, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4.5-preview", input_per_million: 75, output_per_million: 150, cache_read_per_million: 37.5, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4o", input_per_million: 2.5, output_per_million: 10, cache_read_per_million: 1.25, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4o-2024-05-13", input_per_million: 5, output_per_million: 15, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4o-2024-08-06", input_per_million: 2.5, output_per_million: 10, cache_read_per_million: 1.25, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4o-2024-11-20", input_per_million: 2.75, output_per_million: 11, cache_read_per_million: 1.25, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4o-mini", input_per_million: 0.165, output_per_million: 0.66, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-4o-mini-2024-07-18", input_per_million: 0.165, output_per_million: 0.66, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5-2025-08-07", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5-chat", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5-chat-latest", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5-mini", input_per_million: 0.25, output_per_million: 2, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5-mini-2025-08-07", input_per_million: 0.25, output_per_million: 2, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5-nano", input_per_million: 0.05, output_per_million: 0.4, cache_read_per_million: 0.005, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5-nano-2025-08-07", input_per_million: 0.05, output_per_million: 0.4, cache_read_per_million: 0.005, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.1", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.1-2025-11-13", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.1-chat", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.1-chat-2025-11-13", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.2", input_per_million: 1.75, output_per_million: 14, cache_read_per_million: 0.175, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.2-2025-12-11", input_per_million: 1.75, output_per_million: 14, cache_read_per_million: 0.175, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.2-chat", input_per_million: 1.75, output_per_million: 14, cache_read_per_million: 0.175, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.2-chat-2025-12-11", input_per_million: 1.75, output_per_million: 14, cache_read_per_million: 0.175, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.3-chat", input_per_million: 1.75, output_per_million: 14, cache_read_per_million: 0.175, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.4", input_per_million: 2.5, output_per_million: 15, cache_read_per_million: 0.25, cache_write_per_million: 0, input_per_million_above_272k: 5, output_per_million_above_272k: 22.5, cache_read_per_million_above_272k: 0.5 },
  { provider: "azure", model: "gpt-5.4-2026-03-05", input_per_million: 2.5, output_per_million: 15, cache_read_per_million: 0.25, cache_write_per_million: 0, input_per_million_above_272k: 5, output_per_million_above_272k: 22.5, cache_read_per_million_above_272k: 0.5 },
  { provider: "azure", model: "gpt-5.4-mini", input_per_million: 0.75, output_per_million: 4.5, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.4-mini-2026-03-17", input_per_million: 0.75, output_per_million: 4.5, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.4-nano", input_per_million: 0.2, output_per_million: 1.25, cache_read_per_million: 0.02, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.4-nano-2026-03-17", input_per_million: 0.2, output_per_million: 1.25, cache_read_per_million: 0.02, cache_write_per_million: 0 },
  { provider: "azure", model: "gpt-5.5", input_per_million: 5, output_per_million: 30, cache_read_per_million: 0.5, cache_write_per_million: 0, input_per_million_above_272k: 10, output_per_million_above_272k: 45, cache_read_per_million_above_272k: 1 },
  { provider: "azure", model: "gpt-5.5-2026-04-23", input_per_million: 5, output_per_million: 30, cache_read_per_million: 0.5, cache_write_per_million: 0, input_per_million_above_272k: 10, output_per_million_above_272k: 45, cache_read_per_million_above_272k: 1 },
  { provider: "azure", model: "mistral-large-2402", input_per_million: 8, output_per_million: 24, cache_write_per_million: 0 },
  { provider: "azure", model: "mistral-large-latest", input_per_million: 8, output_per_million: 24, cache_write_per_million: 0 },
  { provider: "azure", model: "o1", input_per_million: 15, output_per_million: 60, cache_read_per_million: 7.5, cache_write_per_million: 0 },
  { provider: "azure", model: "o1-2024-12-17", input_per_million: 15, output_per_million: 60, cache_read_per_million: 7.5, cache_write_per_million: 0 },
  { provider: "azure", model: "o1-mini", input_per_million: 1.21, output_per_million: 4.84, cache_read_per_million: 0.605, cache_write_per_million: 0 },
  { provider: "azure", model: "o1-mini-2024-09-12", input_per_million: 1.1, output_per_million: 4.4, cache_read_per_million: 0.55, cache_write_per_million: 0 },
  { provider: "azure", model: "o1-preview", input_per_million: 15, output_per_million: 60, cache_read_per_million: 7.5, cache_write_per_million: 0 },
  { provider: "azure", model: "o1-preview-2024-09-12", input_per_million: 15, output_per_million: 60, cache_read_per_million: 7.5, cache_write_per_million: 0 },
  { provider: "azure", model: "o3", input_per_million: 2, output_per_million: 8, cache_read_per_million: 0.5, cache_write_per_million: 0 },
  { provider: "azure", model: "o3-2025-04-16", input_per_million: 2, output_per_million: 8, cache_read_per_million: 0.5, cache_write_per_million: 0 },
  { provider: "azure", model: "o3-mini", input_per_million: 1.1, output_per_million: 4.4, cache_read_per_million: 0.55, cache_write_per_million: 0 },
  { provider: "azure", model: "o3-mini-2025-01-31", input_per_million: 1.1, output_per_million: 4.4, cache_read_per_million: 0.55, cache_write_per_million: 0 },
  { provider: "azure", model: "o4-mini", input_per_million: 1.1, output_per_million: 4.4, cache_read_per_million: 0.275, cache_write_per_million: 0 },
  { provider: "azure", model: "o4-mini-2025-04-16", input_per_million: 1.1, output_per_million: 4.4, cache_read_per_million: 0.275, cache_write_per_million: 0 },
  { provider: "bedrock", model: "anthropic.claude-3-5-haiku-20241022-v1:0", input_per_million: 0.8, output_per_million: 4, cache_read_per_million: 0.08, cache_write_per_million: 1 },
  { provider: "bedrock", model: "anthropic.claude-3-5-sonnet-20240620-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "anthropic.claude-3-5-sonnet-20241022-v2:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "anthropic.claude-3-7-sonnet-20240620-v1:0", input_per_million: 3.6, output_per_million: 18, cache_read_per_million: 0.36, cache_write_per_million: 4.5 },
  { provider: "bedrock", model: "anthropic.claude-3-7-sonnet-20250219-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "anthropic.claude-3-haiku-20240307-v1:0", input_per_million: 0.25, output_per_million: 1.25, cache_read_per_million: 0.025, cache_write_per_million: 0.3125 },
  { provider: "bedrock", model: "anthropic.claude-3-opus-20240229-v1:0", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "bedrock", model: "anthropic.claude-3-sonnet-20240229-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "anthropic.claude-fable-5", input_per_million: 10, output_per_million: 50, cache_read_per_million: 1, cache_write_per_million: 12.5 },
  { provider: "bedrock", model: "anthropic.claude-haiku-4-5-20251001-v1:0", input_per_million: 1, output_per_million: 5, cache_read_per_million: 0.1, cache_write_per_million: 1.25 },
  { provider: "bedrock", model: "anthropic.claude-instant-v1", input_per_million: 0.8, output_per_million: 2.4, cache_write_per_million: 1 },
  { provider: "bedrock", model: "anthropic.claude-opus-4-1-20250805-v1:0", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "bedrock", model: "anthropic.claude-opus-4-20250514-v1:0", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "bedrock", model: "anthropic.claude-opus-4-5-20251101-v1:0", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "bedrock", model: "anthropic.claude-opus-4-6-v1", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "bedrock", model: "anthropic.claude-opus-4-7", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "bedrock", model: "anthropic.claude-opus-4-8", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "bedrock", model: "anthropic.claude-opus-5", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "bedrock", model: "anthropic.claude-sonnet-4-20250514-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "anthropic.claude-sonnet-4-5-20250929-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "anthropic.claude-sonnet-4-6", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "anthropic.claude-sonnet-5", input_per_million: 2, output_per_million: 10, cache_read_per_million: 0.2, cache_write_per_million: 2.5 },
  { provider: "bedrock", model: "anthropic.claude-v1", input_per_million: 8, output_per_million: 24, cache_write_per_million: 10 },
  { provider: "bedrock", model: "anthropic.claude-v2:1", input_per_million: 8, output_per_million: 24, cache_write_per_million: 10 },
  { provider: "bedrock", model: "apac.anthropic.claude-3-5-sonnet-20240620-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "apac.anthropic.claude-3-5-sonnet-20241022-v2:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "apac.anthropic.claude-3-haiku-20240307-v1:0", input_per_million: 0.25, output_per_million: 1.25, cache_read_per_million: 0.025, cache_write_per_million: 0.3125 },
  { provider: "bedrock", model: "apac.anthropic.claude-3-sonnet-20240229-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "apac.anthropic.claude-haiku-4-5-20251001-v1:0", input_per_million: 1.1, output_per_million: 5.5, cache_read_per_million: 0.11, cache_write_per_million: 1.375 },
  { provider: "bedrock", model: "apac.anthropic.claude-sonnet-4-20250514-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "au.anthropic.claude-haiku-4-5-20251001-v1:0", input_per_million: 1.1, output_per_million: 5.5, cache_read_per_million: 0.11, cache_write_per_million: 1.375 },
  { provider: "bedrock", model: "au.anthropic.claude-opus-4-6-v1", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "au.anthropic.claude-opus-4-7", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "au.anthropic.claude-opus-4-8", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "au.anthropic.claude-opus-5", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "au.anthropic.claude-sonnet-4-5-20250929-v1:0", input_per_million: 3.3, output_per_million: 16.5, cache_read_per_million: 0.33, cache_write_per_million: 4.125 },
  { provider: "bedrock", model: "au.anthropic.claude-sonnet-4-6", input_per_million: 3.3, output_per_million: 16.5, cache_read_per_million: 0.33, cache_write_per_million: 4.125 },
  { provider: "bedrock", model: "au.anthropic.claude-sonnet-5", input_per_million: 2.2, output_per_million: 11, cache_read_per_million: 0.22, cache_write_per_million: 2.75 },
  { provider: "bedrock", model: "claude-sonnet-4-5-20250929-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "eu.anthropic.claude-3-5-haiku-20241022-v1:0", input_per_million: 0.25, output_per_million: 1.25, cache_read_per_million: 0.025, cache_write_per_million: 0.3125 },
  { provider: "bedrock", model: "eu.anthropic.claude-3-5-sonnet-20240620-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "eu.anthropic.claude-3-5-sonnet-20241022-v2:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "eu.anthropic.claude-3-7-sonnet-20250219-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "eu.anthropic.claude-3-haiku-20240307-v1:0", input_per_million: 0.25, output_per_million: 1.25, cache_read_per_million: 0.025, cache_write_per_million: 0.3125 },
  { provider: "bedrock", model: "eu.anthropic.claude-3-opus-20240229-v1:0", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "bedrock", model: "eu.anthropic.claude-3-sonnet-20240229-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "eu.anthropic.claude-fable-5", input_per_million: 11, output_per_million: 55, cache_read_per_million: 1.1, cache_write_per_million: 13.75 },
  { provider: "bedrock", model: "eu.anthropic.claude-haiku-4-5-20251001-v1:0", input_per_million: 1.1, output_per_million: 5.5, cache_read_per_million: 0.11, cache_write_per_million: 1.375 },
  { provider: "bedrock", model: "eu.anthropic.claude-opus-4-1-20250805-v1:0", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "bedrock", model: "eu.anthropic.claude-opus-4-20250514-v1:0", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "bedrock", model: "eu.anthropic.claude-opus-4-5-20251101-v1:0", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "bedrock", model: "eu.anthropic.claude-opus-4-6-v1", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "eu.anthropic.claude-opus-4-7", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "eu.anthropic.claude-opus-4-8", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "eu.anthropic.claude-opus-5", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "eu.anthropic.claude-sonnet-4-20250514-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "eu.anthropic.claude-sonnet-4-5-20250929-v1:0", input_per_million: 3.3, output_per_million: 16.5, cache_read_per_million: 0.33, cache_write_per_million: 4.125 },
  { provider: "bedrock", model: "eu.anthropic.claude-sonnet-4-6", input_per_million: 3.3, output_per_million: 16.5, cache_read_per_million: 0.33, cache_write_per_million: 4.125 },
  { provider: "bedrock", model: "eu.anthropic.claude-sonnet-5", input_per_million: 2.2, output_per_million: 11, cache_read_per_million: 0.22, cache_write_per_million: 2.75 },
  { provider: "bedrock", model: "global.anthropic.claude-fable-5", input_per_million: 10, output_per_million: 50, cache_read_per_million: 1, cache_write_per_million: 12.5 },
  { provider: "bedrock", model: "global.anthropic.claude-haiku-4-5-20251001-v1:0", input_per_million: 1, output_per_million: 5, cache_read_per_million: 0.1, cache_write_per_million: 1.25 },
  { provider: "bedrock", model: "global.anthropic.claude-opus-4-5-20251101-v1:0", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "bedrock", model: "global.anthropic.claude-opus-4-6-v1", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "bedrock", model: "global.anthropic.claude-opus-4-7", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "bedrock", model: "global.anthropic.claude-opus-4-8", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "bedrock", model: "global.anthropic.claude-opus-5", input_per_million: 5, output_per_million: 25, cache_read_per_million: 0.5, cache_write_per_million: 6.25 },
  { provider: "bedrock", model: "global.anthropic.claude-sonnet-4-20250514-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "global.anthropic.claude-sonnet-4-5-20250929-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "global.anthropic.claude-sonnet-4-6", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "global.anthropic.claude-sonnet-5", input_per_million: 2, output_per_million: 10, cache_read_per_million: 0.2, cache_write_per_million: 2.5 },
  { provider: "bedrock", model: "global.openai.gpt-5.6-luna", input_per_million: 0.2, output_per_million: 1.2, cache_read_per_million: 0.02, cache_write_per_million: 0.25, input_per_million_above_272k: 0.4, output_per_million_above_272k: 1.8, cache_read_per_million_above_272k: 0.04, cache_write_per_million_above_272k: 0.5 },
  { provider: "bedrock", model: "global.openai.gpt-5.6-sol", input_per_million: 5, output_per_million: 30, cache_read_per_million: 0.5, cache_write_per_million: 6.25, input_per_million_above_272k: 10, output_per_million_above_272k: 45, cache_read_per_million_above_272k: 1, cache_write_per_million_above_272k: 12.5 },
  { provider: "bedrock", model: "global.openai.gpt-5.6-terra", input_per_million: 2, output_per_million: 12, cache_read_per_million: 0.2, cache_write_per_million: 2.5, input_per_million_above_272k: 4, output_per_million_above_272k: 18, cache_read_per_million_above_272k: 0.4, cache_write_per_million_above_272k: 5 },
  { provider: "bedrock", model: "jp.anthropic.claude-haiku-4-5-20251001-v1:0", input_per_million: 1.1, output_per_million: 5.5, cache_read_per_million: 0.11, cache_write_per_million: 1.375 },
  { provider: "bedrock", model: "jp.anthropic.claude-opus-4-7", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "jp.anthropic.claude-opus-4-8", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "jp.anthropic.claude-opus-5", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "jp.anthropic.claude-sonnet-4-5-20250929-v1:0", input_per_million: 3.3, output_per_million: 16.5, cache_read_per_million: 0.33, cache_write_per_million: 4.125 },
  { provider: "bedrock", model: "jp.anthropic.claude-sonnet-4-6", input_per_million: 3.3, output_per_million: 16.5, cache_read_per_million: 0.33, cache_write_per_million: 4.125 },
  { provider: "bedrock", model: "jp.anthropic.claude-sonnet-5", input_per_million: 2.2, output_per_million: 11, cache_read_per_million: 0.22, cache_write_per_million: 2.75 },
  { provider: "bedrock", model: "openai.gpt-oss-120b-1:0", input_per_million: 0.15, output_per_million: 0.6, cache_write_per_million: 0 },
  { provider: "bedrock", model: "openai.gpt-oss-20b-1:0", input_per_million: 0.07, output_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "bedrock", model: "openai.gpt-oss-safeguard-120b", input_per_million: 0.15, output_per_million: 0.6, cache_write_per_million: 0 },
  { provider: "bedrock", model: "openai.gpt-oss-safeguard-20b", input_per_million: 0.07, output_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "bedrock", model: "us-gov.anthropic.claude-sonnet-4-5-20250929-v1:0", input_per_million: 3.6, output_per_million: 18, cache_read_per_million: 0.36, cache_write_per_million: 4.5 },
  { provider: "bedrock", model: "us.anthropic.claude-3-5-haiku-20241022-v1:0", input_per_million: 0.8, output_per_million: 4, cache_read_per_million: 0.08, cache_write_per_million: 1 },
  { provider: "bedrock", model: "us.anthropic.claude-3-5-sonnet-20240620-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "us.anthropic.claude-3-5-sonnet-20241022-v2:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "us.anthropic.claude-3-7-sonnet-20250219-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "us.anthropic.claude-3-haiku-20240307-v1:0", input_per_million: 0.25, output_per_million: 1.25, cache_read_per_million: 0.025, cache_write_per_million: 0.3125 },
  { provider: "bedrock", model: "us.anthropic.claude-3-opus-20240229-v1:0", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "bedrock", model: "us.anthropic.claude-3-sonnet-20240229-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "us.anthropic.claude-fable-5", input_per_million: 11, output_per_million: 55, cache_read_per_million: 1.1, cache_write_per_million: 13.75 },
  { provider: "bedrock", model: "us.anthropic.claude-haiku-4-5-20251001-v1:0", input_per_million: 1.1, output_per_million: 5.5, cache_read_per_million: 0.11, cache_write_per_million: 1.375 },
  { provider: "bedrock", model: "us.anthropic.claude-opus-4-1-20250805-v1:0", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "bedrock", model: "us.anthropic.claude-opus-4-20250514-v1:0", input_per_million: 15, output_per_million: 75, cache_read_per_million: 1.5, cache_write_per_million: 18.75 },
  { provider: "bedrock", model: "us.anthropic.claude-opus-4-5-20251101-v1:0", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "us.anthropic.claude-opus-4-6-v1", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "us.anthropic.claude-opus-4-7", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "us.anthropic.claude-opus-4-8", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "us.anthropic.claude-opus-5", input_per_million: 5.5, output_per_million: 27.5, cache_read_per_million: 0.55, cache_write_per_million: 6.875 },
  { provider: "bedrock", model: "us.anthropic.claude-sonnet-4-20250514-v1:0", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 3.75 },
  { provider: "bedrock", model: "us.anthropic.claude-sonnet-4-5-20250929-v1:0", input_per_million: 3.3, output_per_million: 16.5, cache_read_per_million: 0.33, cache_write_per_million: 4.125 },
  { provider: "bedrock", model: "us.anthropic.claude-sonnet-4-6", input_per_million: 3.3, output_per_million: 16.5, cache_read_per_million: 0.33, cache_write_per_million: 4.125 },
  { provider: "bedrock", model: "us.anthropic.claude-sonnet-5", input_per_million: 2.2, output_per_million: 11, cache_read_per_million: 0.22, cache_write_per_million: 2.75 },
  { provider: "bedrock", model: "us.openai.gpt-5.6-luna", input_per_million: 0.22, output_per_million: 1.32, cache_read_per_million: 0.022, cache_write_per_million: 0.275, input_per_million_above_272k: 0.44, output_per_million_above_272k: 1.98, cache_read_per_million_above_272k: 0.044, cache_write_per_million_above_272k: 0.55 },
  { provider: "bedrock", model: "us.openai.gpt-5.6-sol", input_per_million: 5.5, output_per_million: 33, cache_read_per_million: 0.55, cache_write_per_million: 6.875, input_per_million_above_272k: 11, output_per_million_above_272k: 49.5, cache_read_per_million_above_272k: 1.1, cache_write_per_million_above_272k: 13.75 },
  { provider: "bedrock", model: "us.openai.gpt-5.6-terra", input_per_million: 2.2, output_per_million: 13.2, cache_read_per_million: 0.22, cache_write_per_million: 2.75, input_per_million_above_272k: 4.4, output_per_million_above_272k: 19.8, cache_read_per_million_above_272k: 0.44, cache_write_per_million_above_272k: 5.5 },
  { provider: "deepseek", model: "deepseek-chat", input_per_million: 0.28, output_per_million: 0.42, cache_read_per_million: 0.028, cache_write_per_million: 0 },
  { provider: "deepseek", model: "deepseek-coder", input_per_million: 0.14, output_per_million: 0.28, cache_write_per_million: 0 },
  { provider: "deepseek", model: "deepseek-r1", input_per_million: 0.55, output_per_million: 2.19, cache_write_per_million: 0 },
  { provider: "deepseek", model: "deepseek-reasoner", input_per_million: 0.28, output_per_million: 0.42, cache_read_per_million: 0.028, cache_write_per_million: 0 },
  { provider: "deepseek", model: "deepseek-v3", input_per_million: 0.27, output_per_million: 1.1, cache_read_per_million: 0.07, cache_write_per_million: 0 },
  { provider: "deepseek", model: "deepseek-v3.2", input_per_million: 0.28, output_per_million: 0.4, cache_write_per_million: 0 },
  { provider: "deepseek", model: "deepseek-v4-flash", input_per_million: 0.44, output_per_million: 1.32, cache_read_per_million: 0.014, cache_write_per_million: 0 },
  { provider: "deepseek", model: "deepseek-v4-pro", input_per_million: 1.32, output_per_million: 3.96, cache_read_per_million: 0.044, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-2.0-flash-001", input_per_million: 0.1, output_per_million: 0.4, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-2.5-computer-use-preview-10-2025", input_per_million: 1.25, output_per_million: 10, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-2.5-flash", input_per_million: 0.3, output_per_million: 2.5, cache_read_per_million: 0.03, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-2.5-flash-lite", input_per_million: 0.1, output_per_million: 0.4, cache_read_per_million: 0.01, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-2.5-flash-lite-preview-06-17", input_per_million: 0.1, output_per_million: 0.4, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-2.5-flash-lite-preview-09-2025", input_per_million: 0.1, output_per_million: 0.4, cache_read_per_million: 0.01, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-2.5-flash-preview-09-2025", input_per_million: 0.3, output_per_million: 2.5, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-2.5-pro", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-3-flash-preview", input_per_million: 0.5, output_per_million: 3, cache_read_per_million: 0.05, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-3-pro-preview", input_per_million: 2, output_per_million: 12, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-3.1-flash-lite", input_per_million: 0.25, output_per_million: 1.5, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-3.1-flash-lite-preview", input_per_million: 0.25, output_per_million: 1.5, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-3.1-pro-preview", input_per_million: 2, output_per_million: 12, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-3.1-pro-preview-customtools", input_per_million: 2, output_per_million: 12, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-3.5-flash", input_per_million: 1.5, output_per_million: 9, cache_read_per_million: 0.15, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-3.5-flash-lite", input_per_million: 0.3, output_per_million: 2.5, cache_read_per_million: 0.03, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-3.6-flash", input_per_million: 0.75, output_per_million: 3.75, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-3.7-flash", input_per_million: 0.75, output_per_million: 3.75, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-exp-1206", input_per_million: 0.3, output_per_million: 2.5, cache_read_per_million: 0.03, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-flash-latest", input_per_million: 0.3, output_per_million: 2.5, cache_read_per_million: 0.03, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-flash-lite-latest", input_per_million: 0.1, output_per_million: 0.4, cache_read_per_million: 0.01, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-gemma-2-27b-it", input_per_million: 0.35, output_per_million: 1.05, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-gemma-2-9b-it", input_per_million: 0.35, output_per_million: 1.05, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-omni-flash-preview", input_per_million: 1.5, output_per_million: 9, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-pro-latest", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-robotics-er-1.5-preview", input_per_million: 0.3, output_per_million: 2.5, cache_read_per_million: 0, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-robotics-er-1.6-preview", input_per_million: 1, output_per_million: 5, cache_write_per_million: 0 },
  { provider: "google", model: "gemini-robotics-er-2-preview", input_per_million: 2, output_per_million: 10, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "groq", model: "gemma-7b-it", input_per_million: 0.05, output_per_million: 0.08, cache_write_per_million: 0 },
  { provider: "groq", model: "llama-3.1-8b-instant", input_per_million: 0.05, output_per_million: 0.08, cache_write_per_million: 0 },
  { provider: "groq", model: "llama-3.3-70b-versatile", input_per_million: 0.59, output_per_million: 0.79, cache_write_per_million: 0 },
  { provider: "minimax", model: "MiniMax-M2", input_per_million: 0.3, output_per_million: 1.2, cache_read_per_million: 0.03, cache_write_per_million: 0 },
  { provider: "minimax", model: "MiniMax-M2.1", input_per_million: 0.3, output_per_million: 1.2, cache_read_per_million: 0.03, cache_write_per_million: 0 },
  { provider: "minimax", model: "MiniMax-M2.1-lightning", input_per_million: 0.3, output_per_million: 2.4, cache_read_per_million: 0.03, cache_write_per_million: 0 },
  { provider: "minimax", model: "MiniMax-M2.5", input_per_million: 0.3, output_per_million: 1.2, cache_read_per_million: 0.03, cache_write_per_million: 0 },
  { provider: "minimax", model: "MiniMax-M2.5-lightning", input_per_million: 0.3, output_per_million: 2.4, cache_read_per_million: 0.03, cache_write_per_million: 0 },
  { provider: "minimax", model: "MiniMax-M3", input_per_million: 0.3, output_per_million: 1.2, cache_read_per_million: 0.06, cache_write_per_million: 0 },
  { provider: "mistral", model: "codestral-2405", input_per_million: 1, output_per_million: 3, cache_write_per_million: 0 },
  { provider: "mistral", model: "codestral-2508", input_per_million: 0.3, output_per_million: 0.9, cache_write_per_million: 0 },
  { provider: "mistral", model: "codestral-latest", input_per_million: 0.3, output_per_million: 0.9, cache_write_per_million: 0 },
  { provider: "mistral", model: "codestral-mamba-latest", input_per_million: 0.25, output_per_million: 0.25, cache_write_per_million: 0 },
  { provider: "mistral", model: "devstral-2512", input_per_million: 0.4, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "mistral", model: "devstral-latest", input_per_million: 0.4, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "mistral", model: "devstral-medium-2507", input_per_million: 0.4, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "mistral", model: "devstral-medium-latest", input_per_million: 0.4, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "mistral", model: "devstral-small-2505", input_per_million: 0.1, output_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "mistral", model: "devstral-small-2507", input_per_million: 0.1, output_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "mistral", model: "devstral-small-latest", input_per_million: 0.1, output_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "mistral", model: "glm-5-2", input_per_million: 1.4, output_per_million: 4.4, cache_read_per_million: 0.14, cache_write_per_million: 0 },
  { provider: "mistral", model: "labs-devstral-small-2512", input_per_million: 0.1, output_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "mistral", model: "magistral-medium-1-2-2509", input_per_million: 2, output_per_million: 5, cache_write_per_million: 0 },
  { provider: "mistral", model: "magistral-medium-2506", input_per_million: 2, output_per_million: 5, cache_write_per_million: 0 },
  { provider: "mistral", model: "magistral-medium-2509", input_per_million: 2, output_per_million: 5, cache_write_per_million: 0 },
  { provider: "mistral", model: "magistral-medium-latest", input_per_million: 2, output_per_million: 5, cache_write_per_million: 0 },
  { provider: "mistral", model: "magistral-small-1-2-2509", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "mistral", model: "magistral-small-2506", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "mistral", model: "magistral-small-latest", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "mistral", model: "ministral-3-14b-2512", input_per_million: 0.2, output_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "mistral", model: "ministral-3-3b-2512", input_per_million: 0.1, output_per_million: 0.1, cache_write_per_million: 0 },
  { provider: "mistral", model: "ministral-3-8b-2512", input_per_million: 0.15, output_per_million: 0.15, cache_write_per_million: 0 },
  { provider: "mistral", model: "ministral-8b-2512", input_per_million: 0.15, output_per_million: 0.15, cache_write_per_million: 0 },
  { provider: "mistral", model: "ministral-8b-latest", input_per_million: 0.15, output_per_million: 0.15, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-large-2402", input_per_million: 4, output_per_million: 12, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-large-2407", input_per_million: 3, output_per_million: 9, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-large-2411", input_per_million: 2, output_per_million: 6, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-large-2512", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-large-3", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-large-latest", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-medium", input_per_million: 2.7, output_per_million: 8.1, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-medium-2312", input_per_million: 2.7, output_per_million: 8.1, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-medium-2505", input_per_million: 0.4, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-medium-2508", input_per_million: 0.4, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-medium-2604", input_per_million: 1.5, output_per_million: 7.5, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-medium-3-1-2508", input_per_million: 0.4, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-medium-3-5", input_per_million: 1.5, output_per_million: 7.5, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-medium-latest", input_per_million: 1.5, output_per_million: 7.5, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-small", input_per_million: 0.1, output_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-small-2603", input_per_million: 0.15, output_per_million: 0.6, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-small-3-2-2506", input_per_million: 0.06, output_per_million: 0.18, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-small-latest", input_per_million: 0.15, output_per_million: 0.6, cache_write_per_million: 0 },
  { provider: "mistral", model: "mistral-tiny", input_per_million: 0.25, output_per_million: 0.25, cache_write_per_million: 0 },
  { provider: "mistral", model: "open-codestral-mamba", input_per_million: 0.25, output_per_million: 0.25, cache_write_per_million: 0 },
  { provider: "mistral", model: "open-mistral-7b", input_per_million: 0.25, output_per_million: 0.25, cache_write_per_million: 0 },
  { provider: "mistral", model: "open-mistral-nemo", input_per_million: 0.3, output_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "mistral", model: "open-mistral-nemo-2407", input_per_million: 0.3, output_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "mistral", model: "open-mixtral-8x22b", input_per_million: 2, output_per_million: 6, cache_write_per_million: 0 },
  { provider: "mistral", model: "open-mixtral-8x7b", input_per_million: 0.7, output_per_million: 0.7, cache_write_per_million: 0 },
  { provider: "mistral", model: "pixtral-12b-2409", input_per_million: 0.15, output_per_million: 0.15, cache_write_per_million: 0 },
  { provider: "mistral", model: "pixtral-large-2411", input_per_million: 2, output_per_million: 6, cache_write_per_million: 0 },
  { provider: "mistral", model: "pixtral-large-latest", input_per_million: 2, output_per_million: 6, cache_write_per_million: 0 },
  { provider: "mistral", model: "zai-glm-5-2", input_per_million: 1.4, output_per_million: 4.4, cache_read_per_million: 0.14, cache_write_per_million: 0 },
  { provider: "moonshot", model: "kimi-k3", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "moonshot", model: "moonshot-v1-128k", input_per_million: 2, output_per_million: 5, cache_write_per_million: 0 },
  { provider: "moonshot", model: "moonshot-v1-128k-0430", input_per_million: 2, output_per_million: 5, cache_write_per_million: 0 },
  { provider: "moonshot", model: "moonshot-v1-128k-vision-preview", input_per_million: 2, output_per_million: 5, cache_write_per_million: 0 },
  { provider: "moonshot", model: "moonshot-v1-32k", input_per_million: 1, output_per_million: 3, cache_write_per_million: 0 },
  { provider: "moonshot", model: "moonshot-v1-32k-0430", input_per_million: 1, output_per_million: 3, cache_write_per_million: 0 },
  { provider: "moonshot", model: "moonshot-v1-32k-vision-preview", input_per_million: 1, output_per_million: 3, cache_write_per_million: 0 },
  { provider: "moonshot", model: "moonshot-v1-8k", input_per_million: 0.2, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "moonshot", model: "moonshot-v1-8k-0430", input_per_million: 0.2, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "moonshot", model: "moonshot-v1-8k-vision-preview", input_per_million: 0.2, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "moonshot", model: "moonshot-v1-auto", input_per_million: 2, output_per_million: 5, cache_write_per_million: 0 },
  { provider: "openai", model: "chat-latest", input_per_million: 5, output_per_million: 30, cache_read_per_million: 0.5, cache_write_per_million: 0 },
  { provider: "openai", model: "chatgpt-4o-latest", input_per_million: 5, output_per_million: 15, cache_write_per_million: 0 },
  { provider: "openai", model: "daybreak-blue-latest", input_per_million: 4, output_per_million: 20, cache_read_per_million: 0.4, cache_write_per_million: 0, input_per_million_above_272k: 8, output_per_million_above_272k: 30, cache_read_per_million_above_272k: 0.8, cache_write_per_million_above_272k: 0 },
  { provider: "openai", model: "daybreak-red-latest", input_per_million: 12.5, output_per_million: 75, cache_read_per_million: 1.25, cache_write_per_million: 0, input_per_million_above_272k: 25, output_per_million_above_272k: 112.5, cache_read_per_million_above_272k: 2.5, cache_write_per_million_above_272k: 0 },
  { provider: "openai", model: "gpt-3.5-turbo", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-3.5-turbo-0125", input_per_million: 0.5, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-3.5-turbo-1106", input_per_million: 1, output_per_million: 2, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-3.5-turbo-16k", input_per_million: 3, output_per_million: 4, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4", input_per_million: 30, output_per_million: 60, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4-0125-preview", input_per_million: 10, output_per_million: 30, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4-0314", input_per_million: 30, output_per_million: 60, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4-0613", input_per_million: 30, output_per_million: 60, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4-1106-preview", input_per_million: 10, output_per_million: 30, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4-turbo", input_per_million: 10, output_per_million: 30, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4-turbo-2024-04-09", input_per_million: 10, output_per_million: 30, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4-turbo-preview", input_per_million: 10, output_per_million: 30, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4.1", input_per_million: 2, output_per_million: 8, cache_read_per_million: 0.5, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4.1-2025-04-14", input_per_million: 2, output_per_million: 8, cache_read_per_million: 0.5, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4.1-mini", input_per_million: 0.4, output_per_million: 1.6, cache_read_per_million: 0.1, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4.1-mini-2025-04-14", input_per_million: 0.4, output_per_million: 1.6, cache_read_per_million: 0.1, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4.1-nano", input_per_million: 0.1, output_per_million: 0.4, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4.1-nano-2025-04-14", input_per_million: 0.1, output_per_million: 0.4, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4o", input_per_million: 2.5, output_per_million: 10, cache_read_per_million: 1.25, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4o-2024-05-13", input_per_million: 5, output_per_million: 15, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4o-2024-08-06", input_per_million: 2.5, output_per_million: 10, cache_read_per_million: 1.25, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4o-2024-11-20", input_per_million: 2.5, output_per_million: 10, cache_read_per_million: 1.25, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4o-mini", input_per_million: 0.15, output_per_million: 0.6, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4o-mini-2024-07-18", input_per_million: 0.15, output_per_million: 0.6, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4o-mini-search-preview", input_per_million: 0.15, output_per_million: 0.6, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4o-mini-search-preview-2025-03-11", input_per_million: 0.15, output_per_million: 0.6, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4o-search-preview", input_per_million: 2.5, output_per_million: 10, cache_read_per_million: 1.25, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-4o-search-preview-2025-03-11", input_per_million: 2.5, output_per_million: 10, cache_read_per_million: 1.25, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5-2025-08-07", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5-chat", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5-chat-latest", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5-mini", input_per_million: 0.25, output_per_million: 2, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5-mini-2025-08-07", input_per_million: 0.25, output_per_million: 2, cache_read_per_million: 0.025, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5-nano", input_per_million: 0.05, output_per_million: 0.4, cache_read_per_million: 0.005, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5-nano-2025-08-07", input_per_million: 0.05, output_per_million: 0.4, cache_read_per_million: 0.005, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5-search-api", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5-search-api-2025-10-14", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.1", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.1-2025-11-13", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.1-chat-latest", input_per_million: 1.25, output_per_million: 10, cache_read_per_million: 0.125, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.2", input_per_million: 1.75, output_per_million: 14, cache_read_per_million: 0.175, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.2-2025-12-11", input_per_million: 1.75, output_per_million: 14, cache_read_per_million: 0.175, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.2-chat-latest", input_per_million: 1.75, output_per_million: 14, cache_read_per_million: 0.175, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.3-chat-latest", input_per_million: 1.75, output_per_million: 14, cache_read_per_million: 0.175, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.4", input_per_million: 2.5, output_per_million: 15, cache_read_per_million: 0.25, cache_write_per_million: 0, input_per_million_above_272k: 5, output_per_million_above_272k: 22.5, cache_read_per_million_above_272k: 0.5 },
  { provider: "openai", model: "gpt-5.4-2026-03-05", input_per_million: 2.5, output_per_million: 15, cache_read_per_million: 0.25, cache_write_per_million: 0, input_per_million_above_272k: 5, output_per_million_above_272k: 22.5, cache_read_per_million_above_272k: 0.5 },
  { provider: "openai", model: "gpt-5.4-mini", input_per_million: 0.75, output_per_million: 4.5, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.4-mini-2026-03-17", input_per_million: 0.75, output_per_million: 4.5, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.4-nano", input_per_million: 0.2, output_per_million: 1.25, cache_read_per_million: 0.02, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.4-nano-2026-03-17", input_per_million: 0.2, output_per_million: 1.25, cache_read_per_million: 0.02, cache_write_per_million: 0 },
  { provider: "openai", model: "gpt-5.5", input_per_million: 5, output_per_million: 30, cache_read_per_million: 0.5, cache_write_per_million: 0, input_per_million_above_272k: 10, output_per_million_above_272k: 45, cache_read_per_million_above_272k: 1 },
  { provider: "openai", model: "gpt-5.5-2026-04-23", input_per_million: 5, output_per_million: 30, cache_read_per_million: 0.5, cache_write_per_million: 0, input_per_million_above_272k: 10, output_per_million_above_272k: 45, cache_read_per_million_above_272k: 1 },
  { provider: "openai", model: "gpt-5.6", input_per_million: 4, output_per_million: 20, cache_read_per_million: 0.4, cache_write_per_million: 5, input_per_million_above_272k: 8, output_per_million_above_272k: 30, cache_read_per_million_above_272k: 0.8, cache_write_per_million_above_272k: 10 },
  { provider: "openai", model: "gpt-5.6-cyber", input_per_million: 12.5, output_per_million: 75, cache_read_per_million: 1.25, cache_write_per_million: 15.625, input_per_million_above_272k: 25, output_per_million_above_272k: 112.5, cache_read_per_million_above_272k: 2.5, cache_write_per_million_above_272k: 31.25 },
  { provider: "openai", model: "gpt-5.6-luna", input_per_million: 0.2, output_per_million: 1.2, cache_read_per_million: 0.02, cache_write_per_million: 0.25, input_per_million_above_272k: 0.4, output_per_million_above_272k: 1.8, cache_read_per_million_above_272k: 0.04, cache_write_per_million_above_272k: 0.5 },
  { provider: "openai", model: "gpt-5.6-sol", input_per_million: 4, output_per_million: 20, cache_read_per_million: 0.4, cache_write_per_million: 5, input_per_million_above_272k: 8, output_per_million_above_272k: 30, cache_read_per_million_above_272k: 0.8, cache_write_per_million_above_272k: 10 },
  { provider: "openai", model: "gpt-5.6-terra", input_per_million: 2, output_per_million: 12, cache_read_per_million: 0.2, cache_write_per_million: 2.5, input_per_million_above_272k: 4, output_per_million_above_272k: 18, cache_read_per_million_above_272k: 0.4, cache_write_per_million_above_272k: 5 },
  { provider: "openai", model: "o1", input_per_million: 15, output_per_million: 60, cache_read_per_million: 7.5, cache_write_per_million: 0 },
  { provider: "openai", model: "o1-2024-12-17", input_per_million: 15, output_per_million: 60, cache_read_per_million: 7.5, cache_write_per_million: 0 },
  { provider: "openai", model: "o3", input_per_million: 2, output_per_million: 8, cache_read_per_million: 0.5, cache_write_per_million: 0 },
  { provider: "openai", model: "o3-2025-04-16", input_per_million: 2, output_per_million: 8, cache_read_per_million: 0.5, cache_write_per_million: 0 },
  { provider: "openai", model: "o3-mini", input_per_million: 1.1, output_per_million: 4.4, cache_read_per_million: 0.55, cache_write_per_million: 0 },
  { provider: "openai", model: "o3-mini-2025-01-31", input_per_million: 1.1, output_per_million: 4.4, cache_read_per_million: 0.55, cache_write_per_million: 0 },
  { provider: "openai", model: "o4-mini", input_per_million: 1.1, output_per_million: 4.4, cache_read_per_million: 0.275, cache_write_per_million: 0 },
  { provider: "openai", model: "o4-mini-2025-04-16", input_per_million: 1.1, output_per_million: 4.4, cache_read_per_million: 0.275, cache_write_per_million: 0 },
  { provider: "qwen", model: "deepseek-v4-flash", input_per_million: 0.2, output_per_million: 0.4, cache_read_per_million: 0.04, cache_write_per_million: 0 },
  { provider: "qwen", model: "deepseek-v4-flash-0731", input_per_million: 0.2, output_per_million: 0.4, cache_read_per_million: 0.04, cache_write_per_million: 0 },
  { provider: "qwen", model: "deepseek-v4-pro", input_per_million: 2.4, output_per_million: 4.8, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "qwen", model: "glm-5.1", input_per_million: 1.4, output_per_million: 4.4, cache_read_per_million: 0.26, cache_write_per_million: 0 },
  { provider: "qwen", model: "glm-5.2", input_per_million: 1.4, output_per_million: 4.4, cache_read_per_million: 0.28, cache_write_per_million: 0 },
  { provider: "qwen", model: "kimi-k2.7-code", input_per_million: 0.95, output_per_million: 4, cache_read_per_million: 0.19, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen-coder", input_per_million: 0.3, output_per_million: 1.5, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen-max", input_per_million: 1.6, output_per_million: 6.4, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen-plus", input_per_million: 0.4, output_per_million: 1.2, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen-plus-2025-01-25", input_per_million: 0.4, output_per_million: 1.2, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen-plus-2025-04-28", input_per_million: 0.4, output_per_million: 1.2, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen-plus-2025-07-14", input_per_million: 0.4, output_per_million: 1.2, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen-turbo", input_per_million: 0.05, output_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen-turbo-2024-11-01", input_per_million: 0.05, output_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen-turbo-2025-04-28", input_per_million: 0.05, output_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen-turbo-latest", input_per_million: 0.05, output_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen3-next-80b-a3b-instruct", input_per_million: 0.15, output_per_million: 1.2, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen3-next-80b-a3b-thinking", input_per_million: 0.15, output_per_million: 1.2, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen3-vl-235b-a22b-instruct", input_per_million: 0.4, output_per_million: 1.6, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen3-vl-235b-a22b-thinking", input_per_million: 0.4, output_per_million: 4, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen3-vl-32b-instruct", input_per_million: 0.16, output_per_million: 0.64, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen3-vl-32b-thinking", input_per_million: 0.16, output_per_million: 2.87, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen3.7-max", input_per_million: 2.5, output_per_million: 7.5, cache_read_per_million: 0.5, cache_write_per_million: 0 },
  { provider: "qwen", model: "qwen3.8-max", input_per_million: 2, output_per_million: 6, cache_read_per_million: 0.25, cache_write_per_million: 2.5 },
  { provider: "qwen", model: "qwq-plus", input_per_million: 0.8, output_per_million: 2.4, cache_write_per_million: 0 },
  { provider: "together", model: "together-ai-21.1b-41b", input_per_million: 0.8, output_per_million: 0.8, cache_write_per_million: 0 },
  { provider: "together", model: "together-ai-4.1b-8b", input_per_million: 0.2, output_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "together", model: "together-ai-41.1b-80b", input_per_million: 0.9, output_per_million: 0.9, cache_write_per_million: 0 },
  { provider: "together", model: "together-ai-8.1b-21b", input_per_million: 0.3, output_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "together", model: "together-ai-81.1b-110b", input_per_million: 1.8, output_per_million: 1.8, cache_write_per_million: 0 },
  { provider: "together", model: "together-ai-up-to-4b", input_per_million: 0.1, output_per_million: 0.1, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-2", input_per_million: 2, output_per_million: 10, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-2-1212", input_per_million: 2, output_per_million: 10, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-2-latest", input_per_million: 2, output_per_million: 10, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-2-vision", input_per_million: 2, output_per_million: 10, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-2-vision-1212", input_per_million: 2, output_per_million: 10, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-2-vision-latest", input_per_million: 2, output_per_million: 10, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-3", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.75, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-3-beta", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.75, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-3-fast-beta", input_per_million: 5, output_per_million: 25, cache_read_per_million: 1.25, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-3-fast-latest", input_per_million: 5, output_per_million: 25, cache_read_per_million: 1.25, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-3-latest", input_per_million: 3, output_per_million: 15, cache_read_per_million: 0.75, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-3-mini", input_per_million: 0.3, output_per_million: 0.5, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-3-mini-beta", input_per_million: 0.3, output_per_million: 0.5, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-3-mini-fast", input_per_million: 0.6, output_per_million: 4, cache_read_per_million: 0.15, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-3-mini-fast-beta", input_per_million: 0.6, output_per_million: 4, cache_read_per_million: 0.15, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-3-mini-fast-latest", input_per_million: 0.6, output_per_million: 4, cache_read_per_million: 0.15, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-3-mini-latest", input_per_million: 0.3, output_per_million: 0.5, cache_read_per_million: 0.075, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4", input_per_million: 3, output_per_million: 15, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4-0709", input_per_million: 3, output_per_million: 15, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4-1-fast", input_per_million: 0.2, output_per_million: 0.5, cache_read_per_million: 0.05, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4-1-fast-non-reasoning", input_per_million: 0.2, output_per_million: 0.5, cache_read_per_million: 0.05, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4-1-fast-non-reasoning-latest", input_per_million: 0.2, output_per_million: 0.5, cache_read_per_million: 0.05, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4-1-fast-reasoning", input_per_million: 0.2, output_per_million: 0.5, cache_read_per_million: 0.05, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4-1-fast-reasoning-latest", input_per_million: 0.2, output_per_million: 0.5, cache_read_per_million: 0.05, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4-fast-non-reasoning", input_per_million: 0.2, output_per_million: 0.5, cache_read_per_million: 0.05, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4-fast-reasoning", input_per_million: 0.2, output_per_million: 0.5, cache_read_per_million: 0.05, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4-latest", input_per_million: 3, output_per_million: 15, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4.20-0309-non-reasoning", input_per_million: 1.25, output_per_million: 2.5, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4.20-0309-reasoning", input_per_million: 1.25, output_per_million: 2.5, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4.20-beta-0309-non-reasoning", input_per_million: 1.25, output_per_million: 2.5, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4.20-beta-0309-reasoning", input_per_million: 1.25, output_per_million: 2.5, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4.20-multi-agent-0309", input_per_million: 1.25, output_per_million: 2.5, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4.20-multi-agent-beta-0309", input_per_million: 1.25, output_per_million: 2.5, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4.3", input_per_million: 1.25, output_per_million: 2.5, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4.3-latest", input_per_million: 1.25, output_per_million: 2.5, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4.5", input_per_million: 2, output_per_million: 6, cache_read_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4.5-latest", input_per_million: 2, output_per_million: 6, cache_read_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-4.6", input_per_million: 2, output_per_million: 6, cache_read_per_million: 0.5, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-beta", input_per_million: 5, output_per_million: 15, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-build-0.1", input_per_million: 1, output_per_million: 2, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-code-fast", input_per_million: 1, output_per_million: 2, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-code-fast-1", input_per_million: 1, output_per_million: 2, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-code-fast-1-0825", input_per_million: 1, output_per_million: 2, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "xai", model: "grok-vision-beta", input_per_million: 5, output_per_million: 15, cache_write_per_million: 0 },
  { provider: "zai", model: "glm-4-32b-0414-128k", input_per_million: 0.1, output_per_million: 0.1, cache_write_per_million: 0 },
  { provider: "zai", model: "glm-4.5", input_per_million: 0.6, output_per_million: 2.2, cache_write_per_million: 0 },
  { provider: "zai", model: "glm-4.5-air", input_per_million: 0.2, output_per_million: 1.1, cache_write_per_million: 0 },
  { provider: "zai", model: "glm-4.5-airx", input_per_million: 1.1, output_per_million: 4.5, cache_write_per_million: 0 },
  { provider: "zai", model: "glm-4.5-x", input_per_million: 2.2, output_per_million: 8.9, cache_write_per_million: 0 },
  { provider: "zai", model: "glm-4.5v", input_per_million: 0.6, output_per_million: 1.8, cache_write_per_million: 0 },
  { provider: "zai", model: "glm-4.6", input_per_million: 0.6, output_per_million: 2.2, cache_read_per_million: 0.11, cache_write_per_million: 0 },
  { provider: "zai", model: "glm-4.7", input_per_million: 0.6, output_per_million: 2.2, cache_read_per_million: 0.11, cache_write_per_million: 0 },
  { provider: "zai", model: "glm-5", input_per_million: 1, output_per_million: 3.2, cache_read_per_million: 0.2, cache_write_per_million: 0 },
  { provider: "zai", model: "glm-5-code", input_per_million: 1.2, output_per_million: 5, cache_read_per_million: 0.3, cache_write_per_million: 0 },
  { provider: "zai", model: "glm-5.1", input_per_million: 1.4, output_per_million: 4.4, cache_read_per_million: 0.26, cache_write_per_million: 0 },
];

export const LITELLM_GENERATED_AT: string = "2026-08-27T19:48:57.736Z";
