import { NextResponse, type NextRequest } from 'next/server';

const PUBLIC_PATH_PREFIXES = [
  '/api/',
  '/_next/static',
  '/_next/image',
  '/brand/',
  '/favicon.ico',
  '/login',
  '/register',
  '/invite',
  '/rankings',
  '/models',
  '/compare',
  '/terms',
  '/privacy',
  '/security',
  '/changelog',
];

// Public SEO/crawler routes (generated by app/sitemap.ts and app/robots.ts).
// Without these, the matcher below lets them reach middleware and they get
// auth-gated → 307 to /login, so crawlers can't fetch the sitemap or robots.
const PUBLIC_EXACT_PATHS = new Set(['/', '/sitemap.xml', '/robots.txt']);

function hasSessionCookie(request: NextRequest): boolean {
  return Boolean(
    request.cookies.get('authjs.session-token')?.value
    ?? request.cookies.get('__Secure-authjs.session-token')?.value,
  );
}

// RSH-53: per-request nonce, Edge-runtime safe (no Buffer). Two UUIDs base64'd
// ≈ 244 bits of entropy.
function buildNonce(): string {
  return btoa(`${crypto.randomUUID()}${crypto.randomUUID()}`).replace(/=+$/, '');
}

// Strict, nonce-based CSP shipped as **report-only** so we can see what a
// locked-down policy would block (reports go to /api/csp-report) before
// enforcing it. The enforced policy still comes from next.config.ts.
//
// Scope note: this is applied only to authenticated routes, which are already
// dynamically rendered. The static marketing pages stay on the next.config CSP
// for now — threading a per-request nonce through them would opt them out of
// static rendering, so tightening those is a deliberate later phase.
function reportOnlyCsp(nonce: string): string {
  return [
    "default-src 'self'",
    `script-src 'self' 'nonce-${nonce}' 'strict-dynamic'`,
    `style-src 'self' 'nonce-${nonce}'`,
    // React components still use style attributes in a few places. Keep that
    // compatibility exception narrowly scoped to attributes during the
    // report-only observation window; <style> elements still require a nonce.
    "style-src-attr 'unsafe-inline'",
    "img-src 'self' data: blob: https:",
    "font-src 'self' data:",
    "connect-src 'self' https://*.sentry.io https://us.posthog.com https://*.posthog.com https://*.i.posthog.com https://api2.amplitude.com https://*.amplitude.com https://api-js.mixpanel.com https://api.mixpanel.com https://*.mixpanel.com wss:",
    "frame-ancestors 'none'",
    "object-src 'none'",
    "base-uri 'self'",
    'report-uri /api/csp-report',
  ].join('; ');
}

function authedResponse(request: NextRequest, nonce: string): NextResponse {
  const csp = reportOnlyCsp(nonce);
  const requestHeaders = new Headers(request.headers);
  requestHeaders.set('x-routeshift-callback-url', `${request.nextUrl.pathname}${request.nextUrl.search}`);
  requestHeaders.set('x-nonce', nonce);
  // Next.js reads the nonce from the request CSP header and applies it to its
  // own framework <script> tags, so they satisfy the report-only policy
  // instead of showing up as violations. This is NOT echoed as an enforced
  // response header — enforcement stays with next.config.ts.
  requestHeaders.set('content-security-policy', csp);

  const response = NextResponse.next({ request: { headers: requestHeaders } });
  response.headers.set('Content-Security-Policy-Report-Only', csp);
  return response;
}

export default function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;
  // Public/static routes: untouched (no per-request nonce → they keep the
  // next.config CSP). Most stay statically rendered; /models is the deliberate
  // exception — it is auth-adaptive (members get the in-shell catalog), so it
  // renders dynamically while still bypassing the nonce path here.
  if (PUBLIC_EXACT_PATHS.has(pathname) || PUBLIC_PATH_PREFIXES.some((prefix) => pathname.startsWith(prefix))) {
    return NextResponse.next();
  }

  if (hasSessionCookie(request)) return authedResponse(request, buildNonce());

  const loginUrl = new URL('/login', request.url);
  loginUrl.searchParams.set('callbackUrl', `${request.nextUrl.pathname}${request.nextUrl.search}`);
  return NextResponse.redirect(loginUrl);
}

export const config = {
  matcher: ['/((?!api/|_next/static|_next/image|brand/|favicon.ico|sitemap.xml|robots.txt|login|register|invite|rankings|models|compare|terms|privacy|security|changelog).*)'],
};
